model_name: "TRPA OLAF model"
model_version: 0.4
scenario_name: "test scenario"
<<<<<<< HEAD
zonal_data: "../data/parcels_2020forolaf.csv" 
=======
zonal_data: "data/parcels_2010forolaf.csv" 
>>>>>>> aa57650d2821231c7eb6f6f6cf93e17fd4701a51
geo_id: "APN"
draws: 30
filter_Undevelopable: "devstatus!='Undevelopable'"

land_uses:
  SFDU_growth:
    name: "single-family dwelling units (growth)"
    market: "housing"
    store_fld: "SFDU_growth"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "(SFDU_growth + UNITS) == 0 & devstatus=='SF'" # can only allocate to parcels that don"t have anything
    total: 638
    value_par: "data/sf_development_model.csv"
    capacity_fn: 1
  MFDU_growth:
    name: "multi-family dwelling units (growth)"
    market: "housing"
    store_fld: "MFDU_growth"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "(MFDU_growth+UNITS) == 0 & devstatus=='MF'" # allocate to parcels that didn"t have anything in the base (but can keep allocating)
    total: 550
    value_par: "data/mf_development_model.csv"
    capacity_fn: "usableland*DENSITY/43560"
  JOBS:
    name: "employment"
    market: "business"
    store_fld: "JOBS_alloc"
    filter_fn: "BUILDING_SQFT==0 & devstatus=='NR'"
    total: 308
    value_par: "data/nr_development_model.csv"
    capacity_fn: 1

# these lines are passed to DataFrame.eval() after allocation
update_block: [
  "SFDU_alloc = SFDU_growth",
  "MFDU_alloc = MFDU_growth",
  "BUILDING_SQFT=BUILDING_SQFT+neighbors_bldsqft_per_unit*(SFDU_alloc+MFDU_alloc+JOBS_alloc)"  
]