model_name: "demonstration model"
model_version: 0.1
scenario_name: "test scenario"
zonal_data: "../data/parcels_2010forolaf.csv" 
geo_id: "APN"
draws: 30
filter_Undevelopable: "devstatus!='Undevelopable'"

land_uses:
  SFDU_growth:
    name: "single-family dwelling units (growth)"
    market: "housing"
    store_fld: "SFDU_growth"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "(SFDU_growth + UNITS + SFDU_decline) == 0 & devstatus=='SF'" # can only allocate to parcels that don"t have anything
    value_fn: "SFDU_trend_const" # term calibrated to match 2014-2019 trends at block group
    total: 638
    dev_para_file: "../data/sf_development_model.csv"
    capacity_fn: 1
  SFDU_decline:
    name: "single-family dwelling units (decline)"
    market: "housing"
    store_fld: "SFDU_decline"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "UNITS==1" # can only de-allocate from parcels that had anything
    value_fn: "-1*SFDU_trend_const" # reverse scoring for declines
    total: 0
    dev_para_file: "../data/sf_development_model.csv"
    capacity_fn: 1
  MFDU_growth:
    name: "multi-family dwelling units (growth)"
    market: "housing"
    store_fld: "MFDU_growth"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "(MFDU_growth+UNITS+MFDU_decline) == 0 & devstatus=='MF'" # allocate to parcels that didn"t have anything in the base (but can keep allocating)
    value_fn: "MFDU_trend_const" # term calibrated to match 2014-2019 trends at block group
    total: 550
    dev_para_file: "../data/mf_development_model.csv"
    capacity_fn: "usableland*DENSITY/43560"
  MFDU_decline:
    name: "multi-family dwelling units (decline)"
    market: "housing"
    store_fld: "MFDU_decline"
    # filter is passed to DataFrame.query(); value is passed to DataFrame.eval()
    filter_fn: "(UNITS - MFDU_decline + MFDU_growth) > 0 & UNITS>0" # can only de-allocate from parcels that had anything
    value_fn: "-1*MFDU_trend_const" # term calibrated to match 2014-2019 trends at block group
    total: 0
    dev_para_file: "../data/mf_development_model.csv"
    capacity_fn: "UNITS- MFDU_decline + MFDU_growth"
  JOBS:
    name: "employment"
    market: "business"
    store_fld: "JOBS_alloc"
    filter_fn: "BUILDING_SQFT==0 & devstatus=='NR'"
    value_fn: "JOBS_trend_const"
    total: 308
    dev_para_file: "../data/nr_development_model.csv"
    capacity_fn: 1

# these lines are passed to DataFrame.eval() after allocation
update_block: [
  "SFDU_alloc = -SFDU_decline + SFDU_growth",
  "MFDU_alloc = -MFDU_decline + MFDU_growth",
  "BUILDING_SQFT=BUILDING_SQFT+neighbors_bldsqft_per_unit*(SFDU_alloc+MFDU_alloc+JOBS_alloc)"  
]